websiteTitle: 'XO'
rootPageId: 1
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
baseVariants: { }
errorHandling: { }
routeEnhancers: { }
routes: { }